### ISSUE TITLE
Packaging - Pyinstaller 

### ISSUE THREAD

**Issue by maskosx** [Mezgrman/TweetPony#14]
Hello there; 

You have one spectacular, user friendly library right there.
I've made a very tiny script that leverages your work; I've only one problem though.
The script doesn't seem to work after packaging; I'm quite new to python.
So I was wondering if you have any idea what to be altered in the .spec file or something so that I'm able to produce a runnable script. 

Thanks in advance.

**Comment by maskosx** [comment]
Hello mate, 
I have managed to address the problem. 
I added one more parameter to both requests.post and requests.get in your api file. 
Verify = 'path to cacert.pem', it wasn't really about including the pem file when packaging. 

Thanks for your help, have a nice year pal. Cheers.

**Comment by Mezgrman** [comment]
Excellent! I think it also said to do that in the link I gave you. I wish you a nice year as well, have fun with TweetPony!
